srr_sample_file: '/home/mcgaugheyd/git/scEiaD/data/sample_run_layout_organism_tech_biosample_organ_2022_03_04.tsv' 
subset_clustering: 'False'
git_dir: '/home/mcgaugheyd/git/scEiaD/' 
bustools_path:  '/home/mcgaugheyd/git/bustools/build/src/'
working_dir: '/data/mcgaugheyd/projects/nei/mcgaughey/scEiaD_2022_02/'
conda_dir: '/data/mcgaugheyd/conda/'
config_abspath: '/data/mcgaugheyd/projects/nei/mcgaughey/scEiaD_2022_02/config.yaml'
fastq_path: '/data/OGVFB_BG/scEiaD'
fi_tsne_dir: '/data/mcgaugheyd/scEiaD'
quant_path: '/data/OGVFB_BG/scEiaD/2021_01_21'
cell_info: 'pipeline_data/cell_info/all_cell_info.tsv'
HVG_var_names: '/home/mcgaugheyd/git/scEiaD/data/scEiaD_2021_03_17_GIGA_HVG.csv'
integration_json: 'integration-config_multiSpecies.yaml'
rson_temp_dir: '/data/mcgaugheyd/projects/nei/mcgaughey/scEiaD_2021_06/rson_tmp/'
samplename_patterns: '/home/mcgaugheyd/git/scEiaD/data/samplename_patterns_2021_06.txt'
droplet_only_org: ['Macaca_fascicularis', 'Gallus_gallus']
dims: '8'
n_features: '5000'
dist: '0.1'
knn: '20'
neighbors: '50'
epochs: '5'
method: 'scVIprojection'
ref_samples: '/home/mcgaugheyd/git/scEiaD/data/human_ref_samples_2022_03.txt'
ambient: 'decontX'
partition: ['universe']
scIB_partition: ['universe']
covariate: 'study_accession'
skip_CT_learning: 'no'
