---
title: "R Notebook"
output: html_notebook
---

# UMAP Extraction
```{r}
library(Seurat)
library(tidyverse)
library(plotly)

load('/Volumes/data/projects/nei/mcgaughey/massive_integrated_eye_scRNA/integratedX.Rdata')
# umap coords
x <- sc_data_integrated@reductions$umap@cell.embeddings %>% as_tibble(rownames = 'Ident') %>% 
  left_join(., sc_data_integrated %>% Idents() %>% enframe('Ident', value = 'Sample'))

plot_ly(x %>% as_tibble() %>% sample_n(10000), x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, color = ~Sample) %>% add_markers()
```



```{r}
embeds <- Embeddings(y[['umap']])
save(embeds, file = 'embeds.Rdata')
load('/Volumes/data/projects/nei/mcgaughey/massive_integrated_eye_scRNA/embeds.Rdata')
embeds %>% head()

samps <- str_extract(embeds %>% row.names(), '(SRS|iPSC_RPE_scRNA_)\\d+')
new <- samps %>% enframe(value = 'sample_accession') %>% left_join(., sra_metadata_extended %>% select(sample_accession, study_accession, Platform, Age, Source, TissueNote) %>% unique())

embeds <- embeds %>% as_tibble()
embeds <- cbind(embeds, new)
embeds <- embeds %>% mutate(Age = case_when(Age == 1e5 ~ 30, TRUE ~ Age))
```

