---
title: "Slingshot Trajectory"
output: html_notebook
---


```{r}
library(Seurat)
library(slingshot)
library(SingleCellExperiment)
library(tidyverse)
library(scattermore)
load('/Volumes/OGVFB_BG/scEiaD/seurat_obj/Mus_musculus_Macaca_fascicularis_Homo_sapiens__n_features5000__counts__TabulaDroplet__batch__scVI__dims8__preFilter__mindist0.1__nneighbors15.umap.Rdata')

load('/Volumes/OGVFB_BG/scEiaD/cluster/Mus_musculus_Macaca_fascicularis_Homo_sapiens__n_features5000__counts__TabulaDroplet__batch__scVI__dims8__preFilter__knn7.cluster.Rdata') 
load('/Volumes/OGVFB_BG/scEiaD/cell_info_labelled.Rdata')
load('/Volumes/OGVFB_BG/scEiaD/umap/Mus_musculus_Macaca_fascicularis_Homo_sapiens__n_features5000__counts__TabulaDroplet__batch__scVI__dims8__preFilter__mindist0.1__nneighbors15.umapFilter.predictions.Rdata')

integrated_obj@meta.data$cluster <- meta[,2] %>% pull(1)


orig_meta <- integrated_obj@meta.data %>% as_tibble(rownames = 'Barcode')

umapX <- left_join(umap,  Embeddings(integrated_obj[['scVI']]) %>% as_tibble(rownames = 'Barcode') ) %>% 
  left_join(., integrated_obj@meta.data %>% as_tibble(rownames = 'Barcode') %>% select(Barcode, cluster))

# umap <- Embeddings(integrated_obj[['scviUMAP']]) %>% as_tibble(rownames = 'Barcode') %>% 
#   left_join(., orig_meta) %>% 
#   left_join(., cell_info_labels %>% 
#               dplyr::rename(Barcode = value) %>% select(-study_accession, -Age, -batch),
#             by = 'Barcode') %>% 
#   left_join(., predictions %>% 
#               as_tibble(rownames = 'Barcode') %>% 
#               select(Barcode, CellType_predict = `predicted.id`)) %>% 
#   mutate(CellType_predict = case_when(is.na(CellType_predict) ~ CellType,
#                                       TRUE ~ CellType_predict))
# integrated_obj@meta.data$CellType <- umap$CellType
# integrated_obj@meta.data$CellType_predict <- umap$CellType_predict
# integrated_obj@meta.data$organism <- umap$organism

```

# Find "starting" cluster
```{r}
umapX %>% group_by(CellType_predict, cluster) %>% dplyr::count() %>% filter(CellType_predict == 'Early RPCs') %>% arrange(-n)
```
```{r, fig.width = 8, fig.height=8}

umapFull <- umap %>% 
  rename(Stage = integration_group,
         UMAP_1 = scviUMAP_1,
         UMAP_2 = scviUMAP_2) %>% 
  mutate(CellType = gsub('Rod Bipolar Cells', 'Bipolar Cells', CellType))
umap <- umapFull  %>% 
  filter(!is.na(CellType), 
         !is.na(study_accession), 
         !CellType %in% c('Astrocytes', 'Horizontal Cells', 'Doublet', 'Doublets', 'Fibroblasts', 'Red Blood Cells'),
         !grepl('RPE|Vascul', CellType))  %>% 
  mutate(Size = case_when(organism == 'Homo sapiens' ~ 0.015,
                          TRUE ~ 0.01)) 

# attach colors to cell types
cell_types <- umap %>% 
  pull(CellType) %>% unique() %>% sort()
type_val <- setNames(pals::alphabet(n = cell_types %>% length()), cell_types)
type_col <- scale_colour_manual(values = type_val)
type_fill <- scale_fill_manual(values = type_val)

red <- 'UMAP'
umap %>% 
  ggplot() + 
  geom_scattermore(aes(x = umap[,paste0(red,'_1')] %>% pull(1), 
                       y = umap[,paste0(red,'_2')] %>% pull(1),  
                       colour = CellType), pointsize = 1, alpha = 0.05) + 
  guides(colour = guide_legend(override.aes = list(size=10, alpha = 1))) + 
  cowplot::theme_cowplot() + 
  type_col + 
  scale_size(guide = 'none') +
  scale_alpha(guide = 'none') +
  #geom_label_repel(data = cluster_labels, aes(x=x, y=y, label = seurat_cluster_CellType_num )) +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) +
  facet_wrap(~cluster) +
  xlab(paste(red, '1')) + ylab(paste(red, '2'))


```

# UMAP by Cell Type
```{r, fig.width = 8, fig.height=8}
umap %>% 
  ggplot() + 
  geom_scattermore(aes(x=umap[,paste0(red,'_1')] %>% pull(1), 
                       y = umap[,paste0(red,'_2')] %>% pull(1), 
                       colour = CellType), pointsize = 0.1, alpha = 0.1) + 
  guides(colour = guide_legend(override.aes = list(size=8, alpha = 1))) + 
  cowplot::theme_cowplot() + 
  #geom_label_repel(data = cluster_labels, aes(x=x, y=y, label = seurat_cluster_CellType_num ), alpha = 0.8, size = 2) +
  type_col + 
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) +
  xlab(paste(red, '1')) + ylab(paste(red, '2'))
```

# UMAP by Age
```{r}
umap %>% 
  filter(Age < 100) %>% 
  ggplot() + 
  geom_scattermore(aes(x= UMAP_1, 
                       y = UMAP_2, 
                       colour = Age), pointsize = 0.1, alpha = 0.1) + 
  guides(colour = guide_legend(override.aes = list(size=8, alpha = 1))) + 
  cowplot::theme_cowplot() + 
  facet_wrap(~organism) +
  scale_color_viridis_c() +
  xlab(paste(red, '1')) + ylab(paste(red, '2'))
```

```{r}
# Got: 
# Error in solve.default(s1 + s2) : system is computationally singular: reciprocal condition number = 1.16521e-18
# trying to add some noise as per: https://github.com/kstreet13/slingshot/issues/35
#sce <- Seurat::as.SingleCellExperiment(integrated_obj)
sce <- SingleCellExperiment(list(counts = integrated_obj@assays$RNA@counts[,umapX$Barcode]),
                                 colData= umapX %>% select(CellType_predict, cluster))


reducedDims(sce) <- list(scVI= umapX %>% select(scVI_1:scVI_8))


set.seed(2534)
sds_in <- apply(reducedDim(sce, "scVI")[,1:8], 2, function(x) jitter(x))

sds <- slingshot(sds_in, 
                 clusterLabels = sce$cluster, 
                 start.clus = 72, 
                 stretch = 0, approx_points = 10000)
save(sds, file = 'sds_massive_approx10000_2020_08_17.Rdata', compress = FALSE)
```


```{r, fig.width=15, fig.height=15}
load('~/data/massive_integrated_eye_scRNA/sds_massive_approx1000__nfeatures2000_dims100_2020_09_06.Rdata')


psTime <- slingshot::slingPseudotime(sds)
#row.names(psTime) <- colnames(sce)
paths <- psTime %>% 
  as_tibble(rownames = 'Barcode') %>% 
  pivot_longer(contains('curve'), 
               names_to = 'Curve', 
               values_to = 'Pseudotime') %>% 
  filter(!is.na(Pseudotime)) %>% 
  mutate(time = cut_interval(Pseudotime, 250)) %>% 
  left_join(umapX) %>% 
  group_by(Curve, time) %>% 
  summarise(UMAP_1 = mean(UMAP_1),
            UMAP_2 = mean(UMAP_2))

psTime %>% 
  as_tibble(rownames = 'Barcode') %>% 
  pivot_longer(contains('curve'), names_to = 'Curve', values_to = 'Pseudotime') %>% 
  filter(!is.na(Pseudotime), Pseudotime < 12) %>% 
  left_join(umapX) %>% 
  ggplot(aes(x=UMAP_1, y = UMAP_2, colour = Pseudotime)) + 
  facet_wrap(~Curve) + 
  geom_scattermore(data = umap, aes(x=UMAP_1, y = UMAP_2), color = 'gray', pointsize = 1, alpha = 0.4) + 
  geom_scattermore(pointsize = 1, alpha = 0.4) + 
  cowplot::theme_cowplot() + 
  scale_color_viridis_c() + 
  xlab('UMAP 1') + ylab('UMAP 2') +
  facet_wrap(~Curve) + 
  geom_path(data = paths, aes(x=UMAP_1, y = UMAP_2), color = 'red', size = 2) 
```

```{r}
psTime %>% 
  as_tibble(rownames = 'Barcode') %>% 
  pivot_longer(contains('curve'), names_to = 'Curve', values_to = 'Pseudotime') %>% 
  filter(!is.na(Pseudotime), Pseudotime < 12) %>% 
  filter(Curve %in% c('curve12','curve4','curve7', 'curve37', 'curve28')) %>% 
  left_join(umapX) %>% 
  ggplot(aes(x=UMAP_1, y = UMAP_2, colour = Pseudotime)) + 
  facet_wrap(~Curve) + 
  geom_scattermore(data = umap, aes(x=UMAP_1, y = UMAP_2), color = 'gray', pointsize = 1, alpha = 0.4) + 
  geom_scattermore(pointsize = 1, alpha = 0.4) + 
  cowplot::theme_cowplot() + 
  scale_color_viridis_c() + 
  xlab('UMAP 1') + ylab('UMAP 2') +
  facet_wrap(~Curve, ncol =3 ) + 
  geom_path(data = paths %>% 
              filter(Curve %in% c('curve12','curve4','curve7', 'curve37','curve28')), aes(x=UMAP_1, y = UMAP_2), color = 'red', size = 2) 
```


```{r, fig.height=10, fig.width=10}
slingshot::slingPseudotime(sds) %>% 
  as_tibble(rownames = 'Barcode') %>% 
  pivot_longer(contains('curve'), names_to = 'Curve', values_to = 'Pseudotime') %>% 
  filter(!is.na(Pseudotime), Pseudotime < 12) %>% 
  left_join(umapFull) %>% filter(Age < 50) %>% 
  filter(organism == 'Mus musculus') %>% 
  ggplot(aes(x=Pseudotime, y = Age, colour = Pseudotime)) + 
  #facet_wrap(~Tech) + 
  geom_jitter(size = 0.2, alpha = 0.4) + 
  cowplot::theme_cowplot() + 
  facet_wrap(~Curve) + 
  scale_color_viridis_c()
```