---
title: "Table 1"
author: David McGaughey
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
output: 
  html_notebook:
    theme: flatly
    toc: true
    code_folding: hide
---

```{r, message=F, warning=F, include=F}
# Load Libraries without printing any warnings or messages
library(tidyverse)
library(formattable)
library(webshot)
library(htmltools)
# all cells
load('/Volumes/data/projects/nei/mcgaughey/massive_integrated_eye_scRNA/cell_info_labelled.Rdata')
# cells after QC (high mito, low gene counts, high gene count)
# load('seurat_obj/Mus_musculus_Macaca_fascicularis_Homo_sapiens__SCT__full__batch.seuratV3.Rdata')

# stats <- seurat__SCT$seurat_list %>% 
#   map(ncol) %>% 
#   map(enframe) %>% 
#   bind_rows(.id='ID') %>% 
#   mutate(ID = gsub('SMARTSeq_v', 'SMARTSeqv', ID)) %>% 
#   mutate(ID = gsub('SMARTerSeq_v', 'SMARTerSeqv', ID)) %>% 
#   separate(ID, c('study_accession', 'Platform', 'Covariate')) %>% 
#   mutate(Platform = gsub('Seqv', 'Seq_v', Platform))

# save(stats, file = 'post_filtering_stats.Rdata')
load('/Volumes/data/projects/nei/mcgaughey/massive_integrated_eye_scRNA/post_filtering_stats.Rdata')

# load('/Volumes/data/projects/nei/mcgaughey/massive_integrated_eye_scRNA/fastMNN_umap_full.Rdata')
study_meta <- read_tsv('~/git/massive_integrated_eye_scRNA/data/GEO_Study_Level_Metadata.tsv')
```

# Table 1
Information on number/composition of studies

`r nrow(cell_info_labels)` cells enter the ring.

`r cell_info_labels$study_accession %>% unique() %>% length()` SRA studies

```{r}
color_bar_factor <- formatter("span",
                              style = function(x) style(
                                display = "block",
                                color = "white",
                                border.radius = "4px",
                                background = c("pink","darkseagreen","violet")[factor(as.character(x))]))

color_bar_factor2 <- formatter("span",
                              style = function(x) style(
                                display = "block",
                                color = "white",
                                border.radius = "4px",
                                background = c("red","green")[factor(as.character(x))]))

export_formattable <- function(f, file, width = "100%", height = NULL, 
                               background = "white", delay = 0.2)
{
  w <- as.htmlwidget(f, width = width, height = height)
  path <- html_print(w, background = background, viewer = NULL)
  url <- paste0("file:///", gsub("\\\\", "/", normalizePath(path)))
  webshot(url,zoom = 4,
          file = file, 
          selector = ".formattable_widget",
          delay = delay)
}

post <- stats %>% rename(`Post QC<br/>Count` = value) %>% 
              select(study_accession, Platform, `Post QC<br/>Count`) %>% 
              group_by(study_accession, Platform) %>% 
              summarise(`Post QC<br/>Count` = sum(`Post QC<br/>Count`))

table01 <- cell_info_labels %>% 
  filter(!is.na(study_accession)) %>% 
  left_join(study_meta) %>% 
  mutate(PMID = as.character(PMID)) %>% 
  mutate(Citation = case_when(is.na(Citation) ~ '',
                              TRUE ~ paste0(substr(Citation, 1, 30), ' ...')),
         PMID = case_when(is.na(PMID) ~ '',
                          TRUE ~ PMID),
         `SRA Accession` = study_accession,
         Labels = case_when(!is.na(CellType) ~ 'Yes',
                              TRUE ~ 'No')) %>% 
  group_by(Citation, PMID, `SRA Accession`, organism, Platform) %>% 
  summarise(Count = n(), Labels = unique(Labels) %>% sort() %>% tail(1)) %>% 
  arrange(organism, -Count) %>% 
  left_join(., post %>% 
              rename(`SRA Accession` = study_accession)) %>% 
  select(Citation:Count, `Post QC<br/>Count`, Labels)

table01$`Post QC<br/>Count`[is.na(table01$`Post QC<br/>Count`)] <- 0
formattable_01 <- table01 %>% 
  formattable(., list(Count = normalize_bar("lightblue"),
                      `Post QC<br/>Count` = normalize_bar("lightblue"),
                      organism = color_bar_factor,
                      Labels = color_bar_factor2,
                      Platform = formatter("span", style = x ~ ifelse(!grepl('SMART|C1', x), 
                                                                      style(font.weight = "bold"), NA))))
formattable_01
export_formattable(formattable_01, '01_table.png')
```
`r table01 %>% filter(Labels == 'Yes') %>% nrow()` studies pre(labelled).

`r sum(table01$"Post QC<br/>Count")` cells after QC.

# Table 2
Pre-labelled cells I've extracted so far
```{r}
table02 <- cell_info_labels %>% 
  mutate(CellType = gsub("Rod Bipolar Cells", "Bipolar Cells", CellType)) %>% 
  filter(!is.na(CellType), !is.na(study_accession), !CellType %in% c('Doublet', 'Doublets', 'Fibroblasts', 'Red Blood Cells')) %>% 
  mutate(organism = case_when(grepl('Homo', organism) ~ 'HS',
                             grepl('Mus', organism) ~ 'MM',
                             TRUE ~ 'MF')) %>% 
  group_by(CellType,organism, study_accession) %>% 
  summarise(Count = n()) %>% 
  summarise(Studies = length(study_accession), Count = sum(Count)) %>% 
  summarise(Species = paste(organism, collapse = ', '), Studies = sum(Studies), Count = sum(Count)) %>% 
  arrange(-Count) %>% 
  formattable(., list(Count = normalize_bar("lightblue")))
table02
export_formattable(table02, '02_table.png')
```

# Session Info
```{r}
devtools::session_info()
```